spring:
  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 10MB
      max-file-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: "fathi3ayari333@gmail.com"
    password: mcdgvyqhnzszyatv
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/back_pfe_app
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: '8000'
  address: 192.168.135.86

